#!/usr/bin/env bash

set -e -x

NAME=${1:-descriptor}

IN=$(mktemp -d)
DS=$(mktemp)
OUT_BASELINE=$(mktemp -d)
OUT_ROUNDTRIP=$(mktemp -d)

cp test/* $IN

protoc --proto_path=$IN/ $NAME.proto --go_out=$OUT_BASELINE --fatal_warnings

go run main.go --root=$IN/ $NAME.proto --output=$OUT_ROUNDTRIP --plugin=$PWD/.bin/protoc-gen-go

git diff --no-index $OUT_BASELINE/gopkg.microglot.org/compiler.go/internal/proto/$NAME.pb.go $OUT_ROUNDTRIP/gopkg.microglot.org/compiler.go/internal/proto/$NAME.pb.go
