// © 2023 Microglot LLC
//
// SPDX-License-Identifier: Apache-2.0

// The idl package contains the general design of the compiler project.
// Interfaces in this package adhere to the constraints of the actual IDL being
// compiled. For example, Reader interface inverts the calling convention of
// the Go standard library reader interface by accepting a length and returning
// a slice of bytes. This is intentional. The goal of this package is to
// eventually be converted into IDL and re-generated by this compiler.
package idl
