# © 2024 Microglot LLC
#
# SPDX-License-Identifier: CC0-1.0

FROM docker.io/golang:1-bookworm

ENV TZ=Etc/UTC

RUN apt-get update && apt-get install --yes \
    shellcheck shfmt \
    jq \
    curl wget gpg \
    make git vim less \
    sudo \
    bash-completion man \
    locales locales-all \
    protobuf-compiler pipx &&\
    pipx install reuse

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ARG USERNAME=mglot
ARG USER_UID=1010
ARG USER_GID=1010

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
