# © 2024 Microglot LLC
#
# SPDX-License-Identifier: Apache-2.0

name: Tag/Release Automation

on:
  push:
    tags:
      - "**"
  workflow_dispatch: {}

jobs:
  build_release:
    name: Build And Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions/cache@v4
        id: tools
        with:
          path: |
            .bin
          key: ${{ runner.os }}-${{ hashFiles('internal/tools/go.sum') }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install build/test tools
        if: steps.tools.outputs.cache-hit != 'true'
        run: make tools
      - name: Unit Tests
        run: make test/unit
      - name: Descriptor Diff Tests
        run: make test/descriptor-diff
      - name: Generate builds
        run: make BUILD_MODE=tag build
      - name: Publish release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
