name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make test
        run: make test
